in:
  type: file
  path_prefix: ./sample_1.csv
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: comment, type: string}
out:
  type: file
  path_prefix: ./result_gz_
  file_ext: csv.gz
  formatter:
    type: csv
    quote_policy: MINIMAL
    newline: LF
  encoders:
  - type: commons-compress
    format: gzip
